### ISSUE TITLE
:memo: Compare with s6

### ISSUE THREAD

**Issue by NicolasCARPi** [linkdd/procfusion#1]
Hello,

I believe the README should also mention [s6-overlay](https://github.com/just-containers/s6-overlay), not only `supervisord`. It would be interesting to describe how this tool compares to it.

For instance, the TOML config is definitely easier to work with than a plethora of small files required for an s6 init.

**Comment by linkdd** [comment]
I didn't know about s6, thank you. I will taker a closer look and add a comparison as well.

At first glance, it seems much more complex to deploy (a bunch of archives to extract for each feature), and aims to be a real init system with all the bells and whistles, while procfusion does not even do dependency management.

**Comment by vzr007** [comment]
It's also would be nice to have a comparison to [dumb-init](https://github.com/Yelp/dumb-init), which is kinda de-facto standard for PID 1 in containers nowadays.
